### ISSUE TITLE
recruit participants for OSS2017

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-2017#1]
Intended venues for recruitment for OSS2017:

- [x] Promotion via the front page of the NCEAS website
- [x] Promotion via the Training Landing page on the NCEAS website
- [x]  An announcement coming from NCEAS to all NCEAS alumni (info@nceas.ucsb.edu list)
    - Particular focus on past OSS participants who will disseminate to colleagues
- [x] Announcements via list serves:
    - [x] ECOLOG (Chris, 1/25, 21474 recipients)
    - [x] DataONE (Amber, 1/26)
    - [x] ESIP (Amber, 1/26)
    - [x] transparency_in_ecoevo@googlegroups.com (Mellor forwarded) (1/26)
    - [ ] Data Carpentry community
- [x] NCEAS newsletter
- [ ] Targeted outreach to colleagues in Gulf Research Communities for email dissemination e.g.
    - [x] Gulf of Mexico Research Initiative Information and Data Cooperative (GOMRI) / Consortium for Ocean Leadership (Amber, 1/26)
    - [x] GRIIDC (Amber, 1/26)
    - [x] Flyers and tweets at the "Gulf of Mexico Oil Spill and Ecosystem Science Conference" Feb 6-9,        2017 in New Orleans (#gulfscienceconference)
    - [x] Ocean Conservancy
    - [ ] Emails to Universities with major Gulf research programs, including U Florida, U Alabama, and Texas A&M Corpus Christi (Harte Research Institute) (also could check WoS for 2016 publications from region and populate a list based on research specificity, i.e. researchers that are active there but at an institution outside region)
    - [x] NOAA National Centers for Environmental Information (Amber, 1/26)
- [x] Twitter campaign from NCEAS, DataONE and instructors participating in the course, using #OSS2017 hashtag
    - [x] @nceas [Tweet](https://twitter.com/nceas/status/823701147860897792)
    - [x] @amoeba [RT'd](https://twitter.com/brycem/status/824032268775657472)
    - [x] @mbjones [RT'd](https://twitter.com/metamattj/status/824010000922050560)
    - [x] @DataONEorg [RT'd]
- [x] Promotion via the training page on the DataONE public website
- [x] Collaboration with NAS on additional outreach / dissemination methods
    - GRP web site?
    - GRP investigator mailing lists
    - GRP funded PIs (especially with synthesis funding)
- [ ] Disseminate short-video intros about the course at midpoint of application period (Chris to create, Amber/Chris to disseminate)

**Comment by aebudden** [comment]
I've created a googledoc with the text that I will use in DataONE mailings.  Please edit as needed and feel free to use as a template for other communications. https://docs.google.com/document/d/1H4eHCfETioBozP0NlenXSRyr1nx0vTujF_6DItEc9i8/edit

**Comment by aebudden** [comment]
Closed as recruitment period is over.
