### ISSUE TITLE
Detecting changes of ecosystems and Gulf coastal communities from the Deepwater Horizon oil spill

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-2017#15]
Author: **Lian Feng**
Topics: ecosystem change, oil spill, geospatial analysis, remote sensing

## Summary of Synthesis

The development of satellite-based Remote Sensing (RS) technology has significantly enriched the science of acquisition and analysis of geo-information. Currently, its integration with other open-source software like R has boosted its application for environment. In this project, I would like to lead my team to explore how to perform raster analysis in R to detect changes of ecosystems and the Gulf coastal communities from 2010 before the Deepwater Horizon oil spill to present day. Specifically, I propose to classify multispectral imagery using different available algorithms in R and utilize knitr package to keep this project reproducible and reusable. 

The first step will involve data searching and downloading. There are numerous remotely sensed data which have been made free to the public online. In this project, I propose to use Landsat images from US Geological Survey’s (USGS) website (https://ers.cr.usgs.gov) because USGS has consistently provided high-quality data from Landsat satellites with high spatial and temporal resolutions. To ensure data suitability for this project, the group will review some key information of available images, like the time when images were captured and cloud cover situation. After learning evaluating conditions of available sources, two datasets from before and after the oil spill will be acquired. 

Secondly, image preprocessing will be performed before raster data analysis. I propose to perform the following preprocessing with the landsat package in R: topographic correction, atmospherically corrected, radiometrically normalized, projection and clipping. In addition, pansharpening will be performed to make use of the greater spatial resolution of the panchromatic band from Landsat-8.
  
The next procedure is land cover classification. Here I recommend unsupervised image classification such that every participant, either has any previous knowledge about the Gulf coastal or not, can be engaged with the actual classification process. If all team members feel familiar with land cover types of the region, a supervised classification can be achieved as well. To conduct unsupervised image classification, we will utilize three algorithms- k-means, clara and random forest, all of which can be accessed through available libraries in R. The team will compare the output classifications using these methods and select the most representable and realistic classification. After selecting the best-practice method for the dataset, the team will perform classification for images obtained before and after the oil spill. Once classified images are obtained, a visual comparison can be performed for change detection.

Through this project, participates will have a visual perception of the impact from oil spills on the coastal ecosystems and they will also learn how to use remotely sensed data to detect changes. On the technical side, the team will gain experiences in retrieving remotely sensed data, pre-processing, raster analysis, mage classification and visualization in open-source R statistical software. As the codes are reproducible, participates will be able to apply this analysis to any raster files with desired applications.

**Comment by aebudden** [comment]
Lian is unable to attend
