### ISSUE TITLE
develop assessments

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-2017#2]
Need pre-, mid-, and post- training assessments instruments, which could/should be compatible with prior years.  To publish on these, we'll also need UCSB IRB approval.
- [ ] Pre-course assessment
- [ ] Mid-course assessment (focused on course correction feedback)
- [ ] Post-course assessment
- [ ] IRB application

We also could consider doing a followup on the 2014 and 2013 course to gauge the impact of those courses on career trajectories.

**Comment by brunj7** [comment]
I gave you access to the Google forms we used for the SNAPP training; it is based on what Stacy did for previous OSS. Feel free to use this as starting point if you go with Google forms: 

Pre:
https://docs.google.com/a/nceas.ucsb.edu/forms/d/1U1f63UNi0MrOpp7BzlTXY1MbjEtjQnJf8eR13soSKgE/edit?usp=sharing

Post (never used it):
https://docs.google.com/a/nceas.ucsb.edu/forms/d/1xUx4ujNTtmWyRIItiYd6UdzabQdSVE3OCGAGgXynR8M/edit?usp=sharing

**Comment by aebudden** [comment]
Thanks Julien.  I'll connect with Stacy too since I believe there was a mid-term evaluation done.

**Comment by zenrabbit** [comment]
I would be keen to see previous evaluations. I can set up private repo for data, and I would love to even a bit of EDA & Viz on it. Could use this repo: https://github.com/cjlortie/OSS2017

**Comment by mbjones** [comment]
This issue was moved to NCEAS/oss-2017-lessons#1
