### ISSUE TITLE
Draft online course schedule

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-2017#3]
Determine if there is an effective way to maintain the course schedule on github in text format with effective formatting.  It can probably be done with Markdown and some judicious use of inline html with CSS styles.

Clearly mark the schedule as a work-in-progress/draft until it is complete.

**Comment by zenrabbit** [comment]
This is a really good idea.  Perhaps a bookdown knit to html. I will explore.

**Comment by zenrabbit** [comment]
R Notebooks, http://rmarkdown.rstudio.com/r_notebooks.html
Jupyter Notebook
Nice tables: kable function from knitr package
http://kbroman.org/knitr_knutshell/pages/figs_tables.html
https://www.r-bloggers.com/creating-nice-tables-using-r-markdown/
Or there is a nice package in R, Gantt, http://stackoverflow.com/questions/3550341/gantt-charts-with-r so we could do schedule as a Gantt Chart.

**Comment by zenrabbit** [comment]
individual RMD files that are thematic proposed on Feb 15th. I will pilot the idea and model a website.

**Comment by zenrabbit** [comment]
Hi Matt,

I did a knit using knitr package, kable function. This is the most common approach to making table using R and sharing online.  It is ok. I think it would be best to split into each week separately. Check repo and you will see. Let me know if that is ok.
