### ISSUE TITLE
Review parking lot issues

### ISSUE THREAD

**Issue by mbjones** [NCEAS/oss-2017#38]
On the first day of OSS 2017, review the concept of the Parking Lot.  In the Parking Lot, we record issues that arise but are not timely to address during another session.  As participants, you can create parking lot issues whenever you have a question or discussion point that would be either off topic or would take too much time to address during the current session.  We will review Parking Lot issues during each morning.  When you create an issue, it may be helpful if you:

- [x] Label the issue with the label [Parking Lot](https://github.com/NCEAS/oss-2017/labels/ParkingLot)
- [x] Are concise
- [x] Provide specific questions
- [x] Provide a list of criteria to be addressed

When the issue has been addressed, the issue can be closed.

**Comment by cnglaspie** [comment]
I think when participants take this course in the future, the instructors should strongly recommend participants get a password manager before they arrive. It would probably streamline things.
