### ISSUE TITLE
collaborative curriculum development

### ISSUE THREAD

**Issue by zenrabbit** [NCEAS/oss-2017#6]

**Comment by zenrabbit** [comment]
**Workshop-level tasks**
- [x] establish agenda for workshop
- [ ] publish current version of schedule
- [x] populate topic-instructor sign-up google sheet: https://docs.google.com/spreadsheets/d/1L2yhFqhNnabJ0yhuJ6kJNbXuoTmof_ZqKqr2axDFEIg/edit#gid=0
- [ ] do an html knit of repo
- [ ] set individual deadlines (even tentative): https://calendar.google.com/calendar/embed?src=nceas.ucsb.edu_nds512p3bulbfn4afeegscdjss%40group.calendar.google.com&ctz=America/Los_Angeles
- [x] provide template
- [ ] prep meta-analysis lesson as template

**Individual-level tasks**
- [ ] prep outline
- [ ] prep learning outcomes
- [ ] check for Gulf Research Case Study
- [ ] work in .rmd file and submit to repo
- [ ] review suggestions from team

**Comment by mbjones** [comment]
This issue was moved to NCEAS/oss-2017-lessons#3
